"""initial schema

Revision ID: 0001
Revises: (nenhuma)
Create Date: 2026-09-09 13:48:05.906760
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("name_normalized", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("frame_type", sa.String(length=64), nullable=True),
        sa.Column("human_readable_type", sa.String(length=128), nullable=True),
        sa.Column("desc", sa.Text(), nullable=False),
        sa.Column("atk", sa.Integer(), nullable=True),
        sa.Column("def", sa.Integer(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("attribute", sa.String(length=16), nullable=True),
        sa.Column("race", sa.String(length=64), nullable=True),
        sa.Column("archetype", sa.String(length=128), nullable=True),
        sa.Column("scale", sa.Integer(), nullable=True),
        sa.Column("linkval", sa.Integer(), nullable=True),
        sa.Column("typeline", sa.JSON(), nullable=True),
        sa.Column("linkmarkers", sa.JSON(), nullable=True),
        sa.Column("tcg_date", sa.Date(), nullable=True),
        sa.Column("ocg_date", sa.Date(), nullable=True),
        sa.Column("konami_id", sa.Integer(), nullable=True),
        sa.Column("has_effect", sa.Boolean(), nullable=False),
        sa.Column("ygoprodeck_url", sa.String(length=512), nullable=True),
        sa.Column("synced_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("card", schema=None) as batch_op:
        batch_op.create_index("ix_card_archetype", ["archetype"], unique=False)
        batch_op.create_index("ix_card_name_normalized", ["name_normalized"], unique=False)

    op.create_table(
        "card_set",
        sa.Column("set_code", sa.String(length=32), nullable=False),
        sa.Column("set_name", sa.String(length=255), nullable=False),
        sa.Column("num_of_cards", sa.Integer(), nullable=True),
        sa.Column("tcg_date", sa.Date(), nullable=True),
        sa.Column("set_image", sa.String(length=512), nullable=True),
        sa.Column("cached_image_path", sa.String(length=512), nullable=True),
        sa.Column("synced_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("set_code"),
    )
    with op.batch_alter_table("card_set", schema=None) as batch_op:
        batch_op.create_index("ix_card_set_name", ["set_name"], unique=False)

    op.create_table(
        "scan_job",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("folder_path", sa.String(length=1024), nullable=False),
        sa.Column("ocr_provider", sa.String(length=32), nullable=False),
        sa.Column("workers", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("total_images", sa.Integer(), nullable=False),
        sa.Column("processed", sa.Integer(), nullable=False),
        sa.Column("skipped", sa.Integer(), nullable=False),
        sa.Column("auto_added", sa.Integer(), nullable=False),
        sa.Column("pending", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'done', 'failed', 'cancelled')", name="ck_scan_job_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sync_state",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "card_image",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=512), nullable=False),
        sa.Column("image_url_small", sa.String(length=512), nullable=True),
        sa.Column("image_url_cropped", sa.String(length=512), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("cached_path", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(["card_id"], ["card.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("card_image", schema=None) as batch_op:
        batch_op.create_index("ix_card_image_card", ["card_id"], unique=False)

    op.create_table(
        "card_print",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("set_code_full", sa.String(length=64), nullable=False),
        sa.Column("set_code_normalized", sa.String(length=64), nullable=False),
        sa.Column("set_prefix", sa.String(length=32), nullable=True),
        sa.Column("set_name", sa.String(length=255), nullable=False),
        sa.Column("rarity", sa.String(length=64), nullable=True),
        sa.Column("rarity_code", sa.String(length=16), nullable=True),
        sa.Column("region", sa.String(length=4), nullable=True),
        sa.Column("number", sa.String(length=8), nullable=True),
        sa.Column("set_price", sa.Float(), nullable=True),
        sa.Column("synced_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["card.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["set_prefix"], ["card_set.set_code"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("card_print", schema=None) as batch_op:
        batch_op.create_index("ix_print_card", ["card_id"], unique=False)
        batch_op.create_index("ix_print_code_normalized", ["set_code_normalized"], unique=False)
        batch_op.create_index("ix_print_prefix", ["set_prefix"], unique=False)

    op.create_table(
        "scan_image",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("ocr_raw", sa.JSON(), nullable=True),
        sa.Column("ocr_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'ok', 'ocr_empty', 'invalid', 'error')",
            name="ck_scan_image_status",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["scan_job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scan_image", schema=None) as batch_op:
        batch_op.create_index("ix_scan_image_job", ["job_id"], unique=False)
        batch_op.create_index("ux_scan_image_hash", ["file_hash"], unique=True)

    op.create_table(
        "collection_item",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("card_print_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("condition", sa.String(length=32), nullable=False),
        sa.Column("edition", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "condition IN ('Near Mint', 'Lightly Played', 'Moderately Played', 'Heavily Played', 'Damaged')",
            name="ck_collection_condition",
        ),
        sa.CheckConstraint(
            "edition IN ('1st Edition', 'Unlimited', 'Limited')", name="ck_collection_edition"
        ),
        sa.CheckConstraint("source IN ('scan', 'manual', 'import')", name="ck_collection_source"),
        sa.CheckConstraint("quantity > 0", name="ck_collection_quantity_positive"),
        sa.ForeignKeyConstraint(["card_id"], ["card.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["card_print_id"], ["card_print.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("collection_item", schema=None) as batch_op:
        batch_op.create_index("ix_collection_card", ["card_id"], unique=False)
        batch_op.create_index("ix_collection_print", ["card_print_id"], unique=False)

    op.create_table(
        "scan_result",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_image_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("card_print_id", sa.Integer(), nullable=True),
        sa.Column("ocr_name_raw", sa.String(length=512), nullable=True),
        sa.Column("ocr_code_raw", sa.String(length=64), nullable=True),
        sa.Column("name_score", sa.Float(), nullable=False),
        sa.Column("code_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("margin", sa.Float(), nullable=False),
        sa.Column("candidates", sa.JSON(), nullable=True),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.Column("collection_item_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "decision IN ('auto', 'pending', 'confirmed', 'rejected', 'unmatched')",
            name="ck_scan_result_decision",
        ),
        sa.ForeignKeyConstraint(["card_id"], ["card.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["card_print_id"], ["card_print.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["collection_item_id"], ["collection_item.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["scan_image_id"], ["scan_image.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scan_result", schema=None) as batch_op:
        batch_op.create_index("ix_scan_result_card", ["card_id"], unique=False)
        batch_op.create_index("ix_scan_result_image", ["scan_image_id"], unique=False)
        batch_op.create_index(
            "ix_scan_result_pending",
            ["decision"],
            unique=False,
            sqlite_where=sa.text("decision = 'pending'"),
        )

    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # A partir daqui é SQL escrito à mão: o autogenerate do Alembic não
    # consegue refletir índices por expressão no SQLite (ele avisa e pula),
    # e não conhece tabelas virtuais FTS5.
    # ------------------------------------------------------------------

    # Unicidade do print. A raridade entra na chave porque a mesma carta pode
    # aparecer duas vezes no mesmo set com raridades diferentes (plano §0.3.3).
    op.execute(
        "CREATE UNIQUE INDEX ux_print ON card_print (card_id, set_code_full, COALESCE(rarity, ''))"
    )

    # Unicidade do item de coleção. O COALESCE existe porque o SQLite trata
    # NULLs como distintos em UNIQUE — sem ele, "carta sem print definido"
    # poderia ser inserida infinitas vezes (plano §4.3).
    op.execute(
        "CREATE UNIQUE INDEX ux_collection "
        "ON collection_item (card_id, COALESCE(card_print_id, -1), "
        "condition, edition, language)"
    )

    # Índice de busca textual: tabela FTS5 de conteúdo externo sobre
    # card.name_normalized, mantida em dia por triggers.
    op.execute(
        """
        CREATE VIRTUAL TABLE card_fts USING fts5(
            name_normalized,
            content='card',
            content_rowid='id',
            tokenize='unicode61 remove_diacritics 2'
        )
        """
    )
    op.execute(
        """
        CREATE TRIGGER card_fts_ai AFTER INSERT ON card BEGIN
            INSERT INTO card_fts(rowid, name_normalized)
            VALUES (new.id, new.name_normalized);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER card_fts_ad AFTER DELETE ON card BEGIN
            INSERT INTO card_fts(card_fts, rowid, name_normalized)
            VALUES ('delete', old.id, old.name_normalized);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER card_fts_au AFTER UPDATE ON card BEGIN
            INSERT INTO card_fts(card_fts, rowid, name_normalized)
            VALUES ('delete', old.id, old.name_normalized);
            INSERT INTO card_fts(rowid, name_normalized)
            VALUES (new.id, new.name_normalized);
        END
        """
    )


def downgrade() -> None:
    # Objetos criados à mão saem primeiro: os triggers dependem de `card`.
    op.execute("DROP TRIGGER IF EXISTS card_fts_au")
    op.execute("DROP TRIGGER IF EXISTS card_fts_ad")
    op.execute("DROP TRIGGER IF EXISTS card_fts_ai")
    op.execute("DROP TABLE IF EXISTS card_fts")
    op.execute("DROP INDEX IF EXISTS ux_collection")
    op.execute("DROP INDEX IF EXISTS ux_print")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan_result", schema=None) as batch_op:
        batch_op.drop_index("ix_scan_result_pending", sqlite_where=sa.text("decision = 'pending'"))
        batch_op.drop_index("ix_scan_result_image")
        batch_op.drop_index("ix_scan_result_card")

    op.drop_table("scan_result")
    with op.batch_alter_table("collection_item", schema=None) as batch_op:
        batch_op.drop_index("ix_collection_print")
        batch_op.drop_index("ix_collection_card")

    op.drop_table("collection_item")
    with op.batch_alter_table("scan_image", schema=None) as batch_op:
        batch_op.drop_index("ux_scan_image_hash")
        batch_op.drop_index("ix_scan_image_job")

    op.drop_table("scan_image")
    with op.batch_alter_table("card_print", schema=None) as batch_op:
        batch_op.drop_index("ix_print_prefix")
        batch_op.drop_index("ix_print_code_normalized")
        batch_op.drop_index("ix_print_card")

    op.drop_table("card_print")
    with op.batch_alter_table("card_image", schema=None) as batch_op:
        batch_op.drop_index("ix_card_image_card")

    op.drop_table("card_image")
    op.drop_table("sync_state")
    op.drop_table("scan_job")
    with op.batch_alter_table("card_set", schema=None) as batch_op:
        batch_op.drop_index("ix_card_set_name")

    op.drop_table("card_set")
    with op.batch_alter_table("card", schema=None) as batch_op:
        batch_op.drop_index("ix_card_name_normalized")
        batch_op.drop_index("ix_card_archetype")

    op.drop_table("card")
    # ### end Alembic commands ###
